### ISSUE TITLE
Match List View - Colours in display are too similar

### ISSUE THREAD

**Issue by aguatemala** [ashish-b10/tournament_manager#71] opened 2018-02-25 17:21 UTC
The colours in the match list view for the "Competing", "Complete" and "Sent to ring" statuses are too similar and they are hard to distinguish for schedulers.

**Comment by ashish-b10** [comment] 2018-09-01 19:40
This is a duplicate of #42. Closing.

**Closed as completed by ashish-b10** 2018-09-01 19:40 UTC
